config/routes.rb
Rails.application.routes.draw do
  get 'hello/index'

  root 'hello#index'

  resource :ips

end

app/models/ip.rb
class Ip < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/controllers/ips_controller.rb
class IpsController < ApplicationController
  def new
  end
  
  def create
    render plain: params[:ip].inspect
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/ips_helper.rb
module IpsHelper
end

app/views/hello/index.html.erb
<h1>Hello#index</h1>
<p>Find me in app/views/hello/index.html.erb</p>

app/views/ips/new.html.erb
<%= form_for :ip, url: ips_path do |f| %>
  <p>
    <%= f.label :staff %><br>
    <%= f.text_field :staff %>
  </p>
 
  <p>
    <%= f.label :ip %><br>
    <%= f.text_area :ip %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LearnRor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>